### ISSUE TITLE
Linux 4.3.y aead algorithm changed -> module doesn't compile

### ISSUE THREAD

**Issue by moonman** [cryptodev-linux/cryptodev-linux#10]
cryptodev module won't compile on linux kernel 4.3
quick history lookup on linux/include/linux/crypto.h shows that algorithm was replaced with a new one
https://github.com/torvalds/linux/commits/master/include/linux/crypto.h

```
ab7/cryptodev_int.h:118:0,
                 from /home/linux-kirkwood-dt/src/cryptodev-linux-da730106c2558c8e0c8e1b1b1812d32ef9574ab7/ioctl.c:53:
/home/linux-kirkwood-dt/src/cryptodev-linux-da730106c2558c8e0c8e1b1b1812d32ef9574ab7/cryptlib.h: In function 'cryptodev_cipher_auth':
/home/linux-kirkwood-dt/src/cryptodev-linux-da730106c2558c8e0c8e1b1b1812d32ef9574ab7/cryptlib.h:43:2: error: implicit declaration of function 'aead_request_set_assoc' [-Werror=implicit-function-declaration]
  aead_request_set_assoc(cdata->async.arequest, len ? sg1 : NULL, len);
  ^
cc1: some warnings being treated as errors

```

**Comment by moonman** [comment]
Just FYI for anyone reading this: there is a patch proposed in the mailing list:
https://mail.gna.org/public/cryptodev-linux-devel/2015-11/msg00003.html
