### ISSUE TITLE
Kernel 3.19 ioctl.c:549:2: error: implicit declaration of function 'get_unused_fd'

### ISSUE THREAD

**Issue by moonman** [cryptodev-linux/cryptodev-linux#6]
There is patch proposed: http://permalink.gmane.org/gmane.comp.handhelds.openembedded.core/60348
```
From 7d71124991030f99965e6e6aaed421115f185adb Mon Sep 17 00:00:00 2001
From: Ricardo Ribalda Delgado <ricardo.ribalda@...>
Date: Mon, 9 Feb 2015 13:51:56 +0100
Subject: [PATCH] ioctl.c: Fix build on 3.19

get_unused_fd() MACRO has been removed on kernel 3.19. Replace by the
actual output of the macro.

Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@...>
---
 ioctl.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/ioctl.c b/ioctl.c
index f26cf93..cf8cc17 100644
--- a/ioctl.c
+++ b/ioctl.c
 @@-529,7 +529,7@@ static int
 clonefd(struct file *filp)
 {
        int ret;
-       ret = get_unused_fd();
+       ret = get_unused_fd_flags(0);
        if (ret >= 0) {
                        get_file(filp);
                        fd_install(ret, filp);
--
2.1.4
```

**Comment by n0-1** [comment]
Hi,

On Mon, Feb 09, 2015 at 06:30:39PM -0800, Oleg Rakhmanov wrote:
> There is patch proposed: http://permalink.gmane.org/gmane.comp.handhelds.openembedded.core/60348

Applied, thanks for reporting!

Best wishes, Phil

**Comment by moonman** [comment]
Thank you
