### PR TITLE
ioctl.c: Fix build with linux 4.13

### PR DESCRIPTION
**Pull request by ribalda**
git/ioctl.c:1127:3: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
   {0, },
    ^
note: (near initialization for 'verbosity_ctl_dir[1]')
git/ioctl.c:1136:3: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
   {0, },
    ^
Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>

### CODE REVIEW

**Comment by cristian-stoica** [comment]
@ribalda What gcc version are you using?

**Comment by ribalda** [comment]
6.3.0

**Comment by cristian-stoica** [comment]
@ribalda It seems the -Werror=designated-init was added in the kernel around 4.11 (c834f0e8a8b) and is triggered even with gcc 5 (but not with 4)

**Comment by ribalda** [comment]
@cristian-stoica any updates on this? Do you need something from my side?

**Comment by cristian-stoica** [comment]
@ribalda @n0-1 Apparently Phil is not watching this thread and I don't have commit rights on this repo. Personally I would add the 'why' from my previous comment in the commit message but otherwise the patch is good to be applied as is.

@nmav can you help with this patch?

**Comment by nmav** [comment]
@cristian-stoica  unfortunately not. I've added you in the project so you can merge it.

**Comment by cristian-stoica** [comment]
@ribalda thanks for your patch

**Comment by ribalda** [comment]
Thank you for this project :)
